// DO NOT EDIT.
// swift-format-ignore-file
// swiftformat:disable all
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: emulator_preview.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Wire-compatible subset of the Android Emulator screenshot API:
/// https://android.googlesource.com/platform/tools/base/+/mirror-goog-studio-main/emulator/proto/emulator_controller.proto
/// Unused response fields are preserved by SwiftProtobuf.
nonisolated struct EmulatorPreview_ImageFormat: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var format: EmulatorPreview_ImageFormat.ImgFormat = .png

  var width: UInt32 = 0

  var height: UInt32 = 0

  var display: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum ImgFormat: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case png // = 0
    case rgba8888 // = 1
    case rgb888 // = 2
    case UNRECOGNIZED(Int)

    init() {
      self = .png
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .png
      case 1: self = .rgba8888
      case 2: self = .rgb888
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .png: return 0
      case .rgba8888: return 1
      case .rgb888: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [EmulatorPreview_ImageFormat.ImgFormat] = [
      .png,
      .rgba8888,
      .rgb888,
    ]

  }

  init() {}
}

nonisolated struct EmulatorPreview_Image: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var format: EmulatorPreview_ImageFormat {
    get {_format ?? EmulatorPreview_ImageFormat()}
    set {_format = newValue}
  }
  /// Returns true if `format` has been explicitly set.
  var hasFormat: Bool {self._format != nil}
  /// Clears the value of `format`. Subsequent reads from it will return its default value.
  mutating func clearFormat() {self._format = nil}

  var image: Data = Data()

  var seq: UInt32 = 0

  var timestampUs: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _format: EmulatorPreview_ImageFormat? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "android.emulation.control"

nonisolated extension EmulatorPreview_ImageFormat: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ImageFormat"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}format\0\u{2}\u{2}width\0\u{1}height\0\u{1}display\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.format) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.width) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.height) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.display) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.format != .png {
      try visitor.visitSingularEnumField(value: self.format, fieldNumber: 1)
    }
    if self.width != 0 {
      try visitor.visitSingularUInt32Field(value: self.width, fieldNumber: 3)
    }
    if self.height != 0 {
      try visitor.visitSingularUInt32Field(value: self.height, fieldNumber: 4)
    }
    if self.display != 0 {
      try visitor.visitSingularUInt32Field(value: self.display, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: EmulatorPreview_ImageFormat, rhs: EmulatorPreview_ImageFormat) -> Bool {
    if lhs.format != rhs.format {return false}
    if lhs.width != rhs.width {return false}
    if lhs.height != rhs.height {return false}
    if lhs.display != rhs.display {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension EmulatorPreview_ImageFormat.ImgFormat: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0PNG\0\u{1}RGBA8888\0\u{1}RGB888\0")
}

nonisolated extension EmulatorPreview_Image: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Image"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}format\0\u{2}\u{3}image\0\u{1}seq\0\u{1}timestampUs\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._format) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.image) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.seq) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self.timestampUs) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._format {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.image.isEmpty {
      try visitor.visitSingularBytesField(value: self.image, fieldNumber: 4)
    }
    if self.seq != 0 {
      try visitor.visitSingularUInt32Field(value: self.seq, fieldNumber: 5)
    }
    if self.timestampUs != 0 {
      try visitor.visitSingularUInt64Field(value: self.timestampUs, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: EmulatorPreview_Image, rhs: EmulatorPreview_Image) -> Bool {
    if lhs._format != rhs._format {return false}
    if lhs.image != rhs.image {return false}
    if lhs.seq != rhs.seq {return false}
    if lhs.timestampUs != rhs.timestampUs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
