name: Mac

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'snapo-app-mac/**'
      - 'VERSION'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'snapo-app-mac/**'
      - 'VERSION'

jobs:
  build:
    runs-on: macos-26

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: '26.1.1'
      - name: Build Snap-O
        working-directory: snapo-app-mac
        run: |
          set -o pipefail
          xcodebuild -project Snap-O.xcodeproj \
                     -scheme Snap-O \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGNING_REQUIRED=NO \
                     build

  swiftlint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:0.63.2@sha256:8db376ff8a26e56fa506b56b8c70ea9c5583dc52d5746ce23b6c2c4d4ee00e31

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 1
      - name: SwiftLint
        working-directory: snapo-app-mac
        run: swiftlint --reporter github-actions-logging --strict

  swiftformat:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 1
      - name: SwiftFormat version
        working-directory: snapo-app-mac
        run: swiftformat --version
      - name: Run SwiftFormat (lint mode)
        working-directory: snapo-app-mac
        run: swiftformat . --lint --config .swiftformat --reporter github-actions-log
